name: Solar System Workflow
on:
    push:
        branches: 
            - main
            - feature/*
    workflow_dispatch: 

env: 
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Test
        strategy:
            fail-fast: false
            matrix:
              node-version: [18, 20]
              operating-system: [ubuntu-latest]
              # exclude:
              #   - node-version: 18
              #     operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        services:
         mongo-dv:
          image: siddharth67/mongo-dv:non-prod
          ports:
            - 27017:27017 
        env: 
          MONGO_URI: 'mongodb//localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up NodeJS version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            - name: Cache the dependecies
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-node-module-${{ hashFiles('package-lock.json') }}
                path: node_modules

            - name: Install Dependencies
              run: |
                 echo "PWD: $PWD"
                 echo "Installing dependencies..."
                 npm install
                 echo "Installation complete"
            
            - name: Unit testing
              id: unit-test-status
              continue-on-error: true
              run: |
                echo "Running unit test using nmp"
                npm test
                # echo "TEST_STATUS=$?" >> $GITHUB_OUTPUT
                ls -lart

            - name: Archive Test Result
              if: always()
              #   if: ${{ failure() && ( steps.unit-test-status.outcome == 'success' || steps.unit-test-status.outcome == 'failure') }}
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result-${{ matrix.operating-system }}-node-${{ matrix.node-version }}
                path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Install NodeJs version 18
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Cache the dependecies
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-node-module-${{ hashFiles('package-lock.json') }}
                path: node_modules

            - name: Install Dependencies
              run: |
                which node
                node --version
                npm --version
                npm install
                ls -lart
            
            - name: Code Coverage
              continue-on-error: true
              run: npm run coverage

            
            - name: Upload code coverage
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage
                path: coverage
                retention-days: 5

    docker:
      name: Logging into docker registry
      runs-on: ubuntu-latest
      permissions: 
        packages: write
      needs: 
        - code-coverage
        - unit-testing
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: login to docker
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

        - name: Test the docker image
          run: |
            docker images
            
            docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP

            echo "Testing the Image URL using wget"
            wget -q -O - localhost:3000/live | grep live

        - name: Push to DockerHub and GHCR
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}





