name: Solar System Workflow
on:
    push:
        branches: 
            - main
            - feature/*
    workflow_dispatch: 

env: 
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Test
        strategy:
            matrix:
              node-version: [18, 19, 20]
              operating-system: [ubuntu-latest, macos-latest]
              exclude:
                - node-version: 18
                  operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up NodeJS version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            
            - name: Install Dependencies
              run: |
                 echo "PWD: $PWD"
                 echo "Installing dependencies..."
                 npm install
                 echo "Installation complete"
            
            - name: Unit testing
              run: |
                echo "Running unit test using nmp"
                npm test

            - name: Archive Test Result
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result-${{ matrix.operating-system }}-node-${{ matrix.node-version }}
                path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Install NodeJs version 18
              uses: actions/setup-node@v4
              with:
                node-version: 18
                
            - name: Install Dependencies
              run: |
                which node
                node --version
                npm --version
                npm install
            
            - name: Code Coverage
              run: npm run coverage
            
            - name: Upload code coverage
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage
                path: coverage
                retention-days: 5